eureka:
  instance:
    hostname: localhost
#    securePortEnabled: true # HTTPS
#    statusPageUrl: https://${eureka.hostname}/info
#    healthCheckUrl: https://${eureka.hostname}/health
#    homePageUrl: https://${eureka.hostname}/
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
#    healthcheck: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://discovery:8761/eureka/

zuul:
  routes:
    api-demo:
      path: /api-demo/*
      serviceId: DEMO
    api-provider: /api-provider/**

server:
  port: 10000

#sidecar:
#  port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true

