server:
  port: 3333
eureka:
  instance:
    hostname: localhost
#    hostname: ribbonsever
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://discovery:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/stayrascal/spring-boot-microservice-config

