server:
  port: 8761
eureka:
  instance:
    hostname: discovery
  client:
    register-with-eureka: false # forbidden register itself
    fetch-registry: false # forbidden register itself
    service-url:
#      defaultzone: http://discovery:${server.port}/eureka/
      defaultzone: http://localhost:${server.port}/eureka/
spring:
  cloud:
    config:
      discovery:
        enabled: true

