filebeat.prospectors:
- input_type: log
  paths:
    - /apps/boot/logs/application.log
  document_type: application
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after

fields:
  application: api-consumer

 output.elasticsearch:
   hosts: ["elasticsearch:9200"]

output.logstash:
  hosts: ["logstash:5044"]
