filebeat.prospectors:
- input_type: log
  paths:
    - /apps/boot/logs/access_log.*.log
  document_type: tomcat

- input_type: log
  paths:
    - /apps/boot/logs/application.log
  document_type: application
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after

fields:
  application: api-admin

output.logstash:
  hosts: ["logstash:5044"]
